### ISSUE TITLE
Can't build Sulky on Ubuntu 15.10 server

### ISSUE THREAD

**Issue by jtgeiger** [huxi/sulky#1]
When using the "./gradlew" script on Ubuntu 15.10 server, the build fails with an error complaining about the Java version number:

de.huxhorn.sulky.version.JavaVersionSpec > JVM 1.8.0_66-internal is at least YeOldeJavaVersion{huge=1, major=8, minor=0, patch=66, preReleaseIdentifier="internal-ea"}

The installed Java version is 1.8.0_66-internal:

$ javac -version
javac 1.8.0_66-internal

$ java -version
openjdk version "1.8.0_66-internal"
OpenJDK Runtime Environment (build 1.8.0_66-internal-b17)
OpenJDK 64-Bit Server VM (build 25.66-b17, mixed mode)

**Comment by huxi** [comment]
Confirmed. Fixed in 607ed2cec1a8d921c901e1afa5fe253683e847b2
